### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by gillestasse** [conzett/jquery.dateRange#4]
After click on the calendar, how can I change the format in the text box ?

For exemple if I want to have : 
26/12/2012
Instead of 
 Wed Dec 26 2012

Or if i want to have it in another language ?

**Comment by conzett** [comment]
Sorry for such a late reply, right now internationalization and formatting are limited to the calendar display itself based on the arrays of month and day names you pass it.

Date formatting is next on the todo list, I'd like to keep the plugin agnostic to external date libraries so that might take a little longer. I will keep you posted.
